### ISSUE TITLE
[BUG] Inspector page not working on iOS

### ISSUE THREAD

**Issue by kharisazhar** [jhomlala/alice#87] opened 2021-07-23 04:37 UTC
**Describe the bug**
Hello is alice support for iOS ?
I try to find docs, but the documentation not contains iOS Support

**To Reproduce**
1. Run debug apps with Alice on iOS
2. Click or shake, then HTTP Inspector not showing 

**Expected behavior**
Show inspector on iOS too like android

**Screenshots**
-

**Flutter doctor**
`fvm: running version "2.0.3"

[✓] Flutter (Channel unknown, 2.0.3, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-ID)
    • Flutter version 2.0.3 at /Users/admin/Documents/core/fvm/2.0.3
    • Framework revision 4d7946a68d (4 months ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • SM A507FN (mobile) • RR8M90G8H5Z               • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)    • 00008030-001D284626FB802E • ios            • iOS 14.4
    • macOS (desktop)    • macos                     • darwin-x64     • Mac OS X 10.15.6 19G2021 darwin-x64
    • Chrome (web)       • chrome                    • web-javascript • Google Chrome 92.0.4515.107

• No issues found!
`

**Alice version**
- Version: ^0.1.12

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 14.4

**Additional context**
Sorry i'm report this bug because no contact or FAQ 

Thanks

**Comment by jhomlala** [comment] 2021-08-07 11:42
@kharisazhar I've tried to run Alice example on iOS 14.x and everything works fine. I see you're using old Flutter version. Can you upgrade to the latest and try again?

Also did you setup Alice properly? Did you provide navigator key?

**Comment by VladislavMitin** [comment] 2021-08-09 12:10
Have the same issue, same reproduce steps

Flutter doctor output:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.

Unable to accept android licenses after flutter upgrade... Problem doesn't relate to this issue.

Tried on emulator IPhone 12 Pro Max

**Comment by jhomlala** [comment] 2021-11-07 10:57
I can't reproduce this on my side. Closing issue. Feel free to answer with reproducible example and I'll reopen it.

**Closed by jhomlala** 2021-11-07 10:57 UTC
Labels: question
