### ISSUE TITLE
Share icon on HTTP Call Details page has no effect

### ISSUE THREAD

**Issue by mattrussell-sonocent** [jhomlala/alice#44] opened 2020-05-07 14:00 UTC
On my iPad (iOS 13.3.1), the floating share button on the HTTP call page has no effect when tapped (Alice version 0.0.30). Another person on my team has seen the same on Android as well at times, although I haven't been able to reproduce.

**Comment by jhomlala** [comment] 2020-05-07 18:46
Duplicate of https://github.com/jhomlala/alice/issues/43

**Comment by jhomlala** [comment] 2020-05-10 08:00
Fixed partially in Alice 0.0.32.

**Closed by jhomlala** 2020-05-10 08:00 UTC
Labels: duplicate
